// apps/react-web-ui-demo/src/routes/components/input.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/input-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/input')({
  staticData: { title: 'Input 输入框' },
  component: Component
})

// apps/vue-web-ui-demo/src/pages/components/input.vue
<route lang="json">
{
  "meta": {
    "title": "输入框"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import InputDemo from '@/components/input-demo/index.vue'

useHead({
  title: () => '输入框'
})
</script>

<template>
  <div class="p-3">
    <InputDemo />
  </div>
</template>
