// apps/vue-app-demo/src/pages/components/avatar.vue
<route lang="json">
{
  "meta": {
    "title": "头像"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import AvatarDemo from '@/components/avatar-demo/index.vue'

useHead({
  title: () => '头像'
})
</script>

<template>
  <div class="p-3">
    <AvatarDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/avatar.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/avatar-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/avatar')({
  staticData: { title: 'Avatar 头像' },
  component: Component
})
