// apps/vue-web-ui-demo/src/pages/components/badge.vue
<route lang="json">
{
  "meta": {
    "title": "徽标"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import BadgeDemo from '@/components/badge-demo/index.vue'

useHead({
  title: () => '徽标'
})
</script>

<template>
  <div class="p-3">
    <BadgeDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/badge.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/badge-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/badge')({ staticData: { title: 'Badge 徽标' }, component: Component })
