// apps/vue-web-ui-demo/src/pages/components/button.vue
<route lang="json">
{
  "meta": {
    "title": "按钮"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import ButtonDemo from '@/components/button-demo/index.vue'

useHead({
  title: () => '按钮'
})
</script>

<template>
  <div class="p-3">
    <ButtonDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/button.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/button-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/button')({
  staticData: { title: 'Button 按钮' },
  component: Component
})
