// apps/vue-web-ui-demo/src/pages/components/checkbox.vue
<route lang="json">
{
  "meta": {
    "title": "复选框"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import CheckboxDemo from '@/components/checkbox-demo/index.vue'
useHead({ title: () => '复选框' })
</script>

<template>
  <div class="p-3"><CheckboxDemo /></div>
</template>

// apps/react-web-ui-demo/src/routes/components/checkbox.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/checkbox-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/checkbox')({
  staticData: { title: 'Checkbox 复选框' },
  component: Component
})
