// apps/vue-web-ui-demo/src/pages/components/dialog.vue
<route lang="json">
{
  "meta": {
    "title": "对话框"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import DialogDemo from '@/components/dialog-demo/index.vue'

useHead({
  title: () => '对话框'
})
</script>

<template>
  <div class="p-3">
    <DialogDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/dialog.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/dialog-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/dialog')({
  staticData: { title: 'Dialog 对话框' },
  component: Component
})
