// apps/vue-app-demo/src/pages/components/drawer.vue
<route lang="json">
{
  "meta": {
    "title": "抽屉"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import DrawerDemo from '@/components/drawer-demo/index.vue'

useHead({
  title: () => '抽屉'
})
</script>

<template>
  <div class="p-3">
    <DrawerDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/drawer.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/drawer-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/drawer')({
  staticData: { title: 'Drawer 抽屉' },
  component: Component
})
