// apps/vue-web-ui-demo/src/pages/components/dropdown.vue
<route lang="json">
{
  "meta": {
    "title": "下拉菜单"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import DropdownDemo from '@/components/dropdown-demo/index.vue'

useHead({
  title: () => '下拉菜单'
})
</script>

<template>
  <div class="p-3">
    <DropdownDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/dropdown.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/dropdown-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/dropdown')({
  staticData: { title: 'Dropdown 下拉菜单' },
  component: Component
})
