// apps/vue-web-ui-demo/src/pages/components/popover.vue
<route lang="json">
{
  "meta": {
    "title": "Popover"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import PopoverDemo from '@/components/popover-demo/index.vue'
useHead({ title: () => 'Popover' })
</script>

<template>
  <div class="p-3"><PopoverDemo /></div>
</template>

// apps/react-web-ui-demo/src/routes/components/popover.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/popover-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/popover')({
  staticData: { title: 'Popover 气泡卡片' },
  component: Component
})
