// apps/vue-web-ui-demo/src/pages/components/segmented.vue
<route lang="json">
{
  "meta": {
    "title": "分段控制器"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import SegmentedDemo from '@/components/segmented-demo/index.vue'
useHead({ title: () => '分段控制器' })
</script>

<template>
  <div class="p-3"><SegmentedDemo /></div>
</template>

// apps/react-web-ui-demo/src/routes/components/segmented.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/segmented-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/segmented')({
  staticData: { title: 'Segmented 分段控制器' },
  component: Component
})
