// apps/vue-app-demo/src/pages/components/select.vue
<route lang="json">
{
  "meta": {
    "title": "下拉选择"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import SelectDemo from '@/components/select-demo/index.vue'

useHead({
  title: () => '下拉选择'
})
</script>

<template>
  <div class="p-3">
    <SelectDemo />
  </div>
</template>

// apps/react-web-ui-demo/src/routes/components/select.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/select-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/select')({
  staticData: { title: 'Select 下拉选择' },
  component: Component
})
