// apps/vue-web-ui-demo/src/pages/components/spinner.vue
<route lang="json">
{
  "meta": {
    "title": "Spinner"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import SpinnerDemo from '@/components/spinner-demo/index.vue'
useHead({ title: () => 'Spinner' })
</script>

<template>
  <div class="p-3"><SpinnerDemo /></div>
</template>

// apps/react-web-ui-demo/src/routes/components/spinner.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/spinner-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/spinner')({
  staticData: { title: 'Spinner 加载指示器' },
  component: Component
})
