// apps/react-web-ui-demo/src/routes/components/context-menu.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/context-menu-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/context-menu')({
  staticData: { title: 'ContextMenu 右键菜单' },
  component: Component
})

// apps/vue-app-demo/src/pages/components/context-menu.vue
<route lang="json">
{
  "meta": {
    "title": "右键菜单"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import ContextMenuDemo from '@/components/context-menu-demo/index.vue'

useHead({
  title: () => '右键菜单'
})
</script>

<template>
  <div class="p-3">
    <ContextMenuDemo />
  </div>
</template>
