// apps/react-web-ui-demo/src/routes/components/input-number.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/input-number-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/input-number')({
  staticData: { title: 'InputNumber 数字输入框' },
  component: Component
})

// apps/vue-app-demo/src/pages/components/input-number.vue
<route lang="json">
{
  "meta": {
    "title": "数字输入框"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import InputNumberDemo from '@/components/input-number-demo/index.vue'

useHead({
  title: () => '数字输入框'
})
</script>

<template>
  <div class="p-3">
    <InputNumberDemo />
  </div>
</template>
