// apps/react-web-ui-demo/src/routes/components/textarea.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/textarea-demo'

function Component() {
  return (
    <div className="p-3">
      <DemoComponent />
    </div>
  )
}

export const Route = createFileRoute('/components/textarea')({
  staticData: { title: 'Textarea 文本域' },
  component: Component
})

// apps/vue-app-demo/src/pages/components/textarea.vue
<route lang="json">
{
  "meta": {
    "title": "文本域"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import TextareaDemo from '@/components/textarea-demo/index.vue'

useHead({
  title: () => '文本域'
})
</script>

<template>
  <div class="p-3">
    <TextareaDemo />
  </div>
</template>
