// apps/react-web-ui-demo/src/routes/components/toast.tsx
import { createFileRoute } from '@tanstack/react-router'

import DemoComponent from '@/components/toast-demo'

function Component() {
  return (
    <>
      <DemoComponent />
    </>
  )
}

export const Route = createFileRoute('/components/toast')({
  staticData: { title: 'Toast 通知' },
  component: Component
})

// apps/vue-app-demo/src/pages/components/toast.vue
<route lang="json">
{
  "meta": {
    "title": "Toast 通知"
  }
}
</route>

<script setup lang="ts">
import { useHead } from '@unhead/vue'

import ToastDemo from '@/components/toast-demo/index.vue'

useHead({
  title: () => 'Toast 通知'
})
</script>

<template>
  <div class="p-3">
    <ToastDemo />
  </div>
</template>
