// apps/react-web-ui-demo/src/components/slider-demo/index.tsx
import { useState } from 'react'

function SliderDemo() {
  const [standardValue, setStandardValue] = useState(36)
  const [markedValue, setMarkedValue] = useState(50)
  const [inputValue, setInputValue] = useState(40)
  const [changeValue, setChangeValue] = useState(40)
  const [verticalValue, setVerticalValue] = useState(60)
  const [verticalMarkedValue, setVerticalMarkedValue] = useState(50)

  return (
    <div className="slider-demo">
      <h1>滑块</h1>
      <section>
        <h2>基础样式</h2>
        <div className="examples">
          <div className="example">
            <web-ui-slider value={standardValue} onInput={event => setStandardValue(event.currentTarget.value)} />
          </div>
          <div className="example">
            <web-ui-slider value={42} />
          </div>
          <div className="example">
            <web-ui-slider value={42} disabled />
          </div>
        </div>
      </section>
      <section>
        <h2>刻度</h2>
        <div className="examples">
          <div className="example">
            <web-ui-slider
              value={markedValue}
              step={10}
              marks
              onInput={event => setMarkedValue(event.currentTarget.value)}
            />
          </div>
          <div className="example">
            <web-ui-slider value={70} step={10} marks />
          </div>
          <div className="example">
            <web-ui-slider value={50} step={10} marks disabled />
          </div>
        </div>
      </section>
      <section>
        <h2>范围与事件</h2>
        <div className="event-example">
          <web-ui-slider
            value={inputValue}
            min={10}
            max={90}
            step={5}
            marks
            onInput={event => setInputValue(event.currentTarget.value)}
            onChange={event => setChangeValue(event.currentTarget.value)}
          />
          <output>
            input: {inputValue} / change: {changeValue}
          </output>
        </div>
      </section>
      <section>
        <h2>垂直</h2>
        <div className="vertical-examples">
          <div className="example">
            <web-ui-slider
              vertical
              value={verticalValue}
              onInput={event => setVerticalValue(event.currentTarget.value)}
            />
            <span className="label">{verticalValue}</span>
          </div>
          <div className="example">
            <web-ui-slider
              vertical
              value={verticalMarkedValue}
              step={10}
              marks
              onInput={event => setVerticalMarkedValue(event.currentTarget.value)}
            />
            <span className="label">{verticalMarkedValue}</span>
          </div>
          <div className="example">
            <web-ui-slider vertical value={50} disabled />
            <span className="label">禁用</span>
          </div>
        </div>
      </section>
      <style>{`
        .slider-demo { max-width: 920px; }
        section { margin-top: 28px; }
        .examples { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px; padding: 20px 0; }
        .example { display: flex; gap: 12px; align-items: center; min-width: 0; }
        .vertical-examples { display: flex; gap: 32px; align-items: flex-start; padding: 20px 0; }
        .label { font-size: 14px; color: #5d6675; white-space: nowrap; }
        .event-example { display: flex; gap: 16px; align-items: center; padding: 20px 0; }
        output { font-size: 14px; color: #5d6675; }
        web-ui-slider:not([vertical]) { width: 100%; }
        web-ui-slider[vertical] { height: 200px; }
        @media (width <= 700px) { .examples { grid-template-columns: 1fr; } .event-example { flex-direction: column; align-items: flex-start; } }
      `}</style>
    </div>
  )
}
export default SliderDemo

// apps/vue-app-demo/src/components/slider-demo/index.vue
<script setup lang="ts">
import { ref } from 'vue'

const standardValue = ref(36)
const markedValue = ref(50)
const inputValue = ref(40)
const changeValue = ref(40)
const verticalValue = ref(60)
const verticalMarkedValue = ref(50)

function updateStandardValue(event: Event) {
  standardValue.value = getSliderValue(event)
}

function updateMarkedValue(event: Event) {
  markedValue.value = getSliderValue(event)
}

function updateInputValue(event: Event) {
  inputValue.value = getSliderValue(event)
}

function updateChangeValue(event: Event) {
  changeValue.value = getSliderValue(event)
}

function updateVerticalValue(event: Event) {
  verticalValue.value = getSliderValue(event)
}

function updateVerticalMarkedValue(event: Event) {
  verticalMarkedValue.value = getSliderValue(event)
}

function getSliderValue(event: Event): number {
  const source = event.currentTarget
  if (!isSlider(source)) return 0
  return source.value
}

function isSlider(target: EventTarget | null): target is HTMLElement & { value: number } {
  return (
    target instanceof HTMLElement &&
    target.localName === 'web-ui-slider' &&
    typeof (target as { value?: unknown }).value === 'number'
  )
}
</script>

<template>
  <div class="slider-demo">
    <h1>滑块</h1>

    <section>
      <h2>基础样式</h2>
      <div class="examples">
        <div class="example"><web-ui-slider :value="standardValue" @input="updateStandardValue" /></div>
        <div class="example"><web-ui-slider :value="42" /></div>
        <div class="example"><web-ui-slider :value="42" disabled /></div>
      </div>
    </section>

    <section>
      <h2>刻度</h2>
      <div class="examples">
        <div class="example"><web-ui-slider :value="markedValue" :step="10" marks @input="updateMarkedValue" /></div>
        <div class="example"><web-ui-slider :value="70" :step="10" marks /></div>
        <div class="example"><web-ui-slider :value="50" :step="10" marks disabled /></div>
      </div>
    </section>

    <section>
      <h2>范围与事件</h2>
      <div class="event-example">
        <web-ui-slider
          :value="inputValue"
          :min="10"
          :max="90"
          :step="5"
          marks
          @input="updateInputValue"
          @change="updateChangeValue"
        />
        <output>input: {{ inputValue }} / change: {{ changeValue }}</output>
      </div>
    </section>

    <section>
      <h2>垂直</h2>
      <div class="vertical-examples">
        <div class="example">
          <web-ui-slider vertical :value="verticalValue" @input="updateVerticalValue" />
          <span class="label">{{ verticalValue }}</span>
        </div>
        <div class="example">
          <web-ui-slider vertical :value="verticalMarkedValue" :step="10" marks @input="updateVerticalMarkedValue" />
          <span class="label">{{ verticalMarkedValue }}</span>
        </div>
        <div class="example">
          <web-ui-slider vertical :value="50" disabled />
          <span class="label">禁用</span>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.slider-demo {
  max-width: 920px;
}

section {
  margin-top: 28px;
}

.examples {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 24px;
  padding: 20px 0;
}

.example {
  display: flex;
  gap: 12px;
  align-items: center;
  min-width: 0;
}

.vertical-examples {
  display: flex;
  gap: 32px;
  align-items: flex-start;
  padding: 20px 0;
}

.label {
  font-size: 14px;
  color: #5d6675;
  white-space: nowrap;
}

.event-example {
  display: flex;
  gap: 16px;
  align-items: center;
  padding: 20px 0;
}

output {
  font-size: 14px;
  color: #5d6675;
}

web-ui-slider:not([vertical]) {
  width: 100%;
}

web-ui-slider[vertical] {
  height: 200px;
}

@media (width <= 700px) {
  .examples {
    grid-template-columns: 1fr;
  }

  .event-example {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
