// apps/vue-web-ui-demo/src/type-fixtures/event-typing.vue
<script setup lang="ts">
// Vue 事件类型回归护栏：锁定「宿主化 $events + 局部 HTMLAttributes」类型契约的关键场景，
// 随每次 vue-tsc --build 被检查。
// 局限：vue-tsc 对组件上未声明 emit/prop 的属性和事件会回退到 $attrs 放行（$event 为 any），
// 因此本文件无法对「非 web-ui 组件被全局污染」做负向断言；该契约由 types/vue.ts
// 不再全局扩展 ComponentCustomProps 结构保证，并由 docs/agents/web-ui.md 约束。
import type {
  WebUiCheckboxGroup,
  WebUiCollapse,
  WebUiDialog,
  WebUiEvent,
  WebUiEventName,
  WebUiSegmented,
  WebUiSwitch
} from '@greypan/web-ui'
import { ref } from 'vue'

// 1. 标准事件的 target/currentTarget 收窄到 host，value/checked 精确推导。
function onSegmentedInput(event: WebUiEvent<WebUiSegmented, 'input'>) {
  const value: string = event.target.value
  valueRef.value = value
}
function onSwitchChange(event: WebUiEvent<WebUiSwitch, 'change'>) {
  const checked: boolean = event.currentTarget.checked
  checkedRef.value = checked
}

// 1b. 复合控件 group 的 change 同样收窄到 group 实例，value 为 string[]。
function onGroupChange(event: WebUiEvent<WebUiCheckboxGroup, 'change'>) {
  const values: string[] = event.target.value
  groupVals.value = values
}

// 2. kebab-case CustomEvent 的 detail 精确推导。
function onDialogOpenChange(event: WebUiEvent<WebUiDialog, 'open-change'>) {
  const open: boolean = event.detail.open
  dialogOpen.value = open
}

// 2a. collapse 的 open-change 同样收窄到 collapse 实例。
function onCollapseOpenChange(event: WebUiEvent<WebUiCollapse, 'open-change'>) {
  const open: boolean = event.currentTarget.open
  collapseOpen.value = open
}

// 2b. `$events` 中声明的 string 事件名可赋值；其他 string 被拒绝。
const dialogOpenChangeEventName: WebUiEventName<WebUiDialog> = 'open-change'
void dialogOpenChangeEventName
// @ts-expect-error web-ui-dialog 未声明 invalid-event
const invalidDialogEventName: WebUiEventName<WebUiDialog> = 'invalid-event'
void invalidDialogEventName

// 3. 具体 Custom Element 模板 ref 类型。
const segmentedRef = ref<WebUiSegmented>()

const valueRef = ref('')
const checkedRef = ref(false)
const groupVals = ref<string[]>([])
const dialogOpen = ref(false)
const collapseOpen = ref(false)
const clickCount = ref(0)
</script>

<template>
  <!-- 1. inline handler 直接使用推导的 $event.target/currentTarget，无需 cast -->
  <web-ui-segmented :value="valueRef" @input="valueRef = $event.target.value" />
  <web-ui-switch :checked="checkedRef" @change="checkedRef = $event.target.checked" />
  <web-ui-segmented @input="onSegmentedInput" />
  <web-ui-switch @change="onSwitchChange" />

  <!-- 1b. group 的 inline 与命名 handler 均无 cast -->
  <web-ui-checkbox-group :value="groupVals" @change="groupVals = $event.target.value">
    <web-ui-checkbox value="a">A</web-ui-checkbox>
  </web-ui-checkbox-group>
  <web-ui-checkbox-group @change="onGroupChange" />

  <!-- 2. kebab 自定义事件：$event.detail 精确类型 -->
  <web-ui-dialog :open="dialogOpen" no-escape-close @open-change="dialogOpen = $event.detail.open" />
  <web-ui-dialog @open-change="onDialogOpenChange" />
  <web-ui-collapse :open="collapseOpen" keep-mounted @open-change="collapseOpen = $event.detail.open">
    <button>Trigger</button>
    <div slot="content">Content</div>
  </web-ui-collapse>
  <web-ui-collapse @open-change="onCollapseOpenChange" />

  <!-- 3. 具体 Custom Element ref -->
  <web-ui-segmented ref="segmentedRef" />

  <!-- 4. 未声明 $events 的组件仍支持原生 click/focus 绑定 -->
  <web-ui-button @click="clickCount = clickCount + 1" @focus="clickCount = clickCount + 1">A</web-ui-button>
</template>

// apps/react-web-ui-demo/src/type-fixtures/event-typing.tsx
import type { WebUiDialog, WebUiEventName, WebUiSegmented, WebUiSwitch } from '@greypan/web-ui'
import { useRef, useState } from 'react'

// React 事件类型回归护栏：锁定「宿主化 $events + HTMLAttributes」类型契约的关键场景，
// 随每次 `vp check`（oxlint 类型感知）被检查。
// 正向断言验证精确推导；`@ts-expect-error` 负向断言验证未知属性/事件/别名被拒绝。
export function EventTypingFixture() {
  const segmentedRef = useRef<WebUiSegmented>(null)
  const switchRef = useRef<WebUiSwitch>(null)
  const dialogRef = useRef<WebUiDialog>(null)
  const [collapseOpen, setCollapseOpen] = useState(false)

  // `$events` 中声明的 kebab-case event name 可赋值；其他 string 被拒绝。
  const dialogOpenChangeEventName: WebUiEventName<WebUiDialog> = 'open-change'
  void dialogOpenChangeEventName
  // @ts-expect-error web-ui-dialog 未声明 invalid-event
  const invalidDialogEventName: WebUiEventName<WebUiDialog> = 'invalid-event'
  void invalidDialogEventName

  return (
    <>
      {/* 1a. 标准事件 currentTarget 收窄到 host，value/checked 精确推导 */}
      <web-ui-segmented
        onInput={e => {
          const value: string = e.currentTarget.value
          void value
        }}
      />
      <web-ui-switch
        onChange={e => {
          const checked: boolean = e.currentTarget.checked
          void checked
        }}
      />

      {/* 1b. React SyntheticEvent 的 target 遵循原生语义（EventTarget），不承诺为组件实例 */}
      <web-ui-segmented
        onInput={e => {
          const ct: WebUiSegmented = e.currentTarget
          void ct
          // @ts-expect-error target 是 EventTarget，不是组件实例
          const t: WebUiSegmented = e.target
          void t
        }}
      />

      {/* 1c. 无 $events 的组件仍支持原生 click/focus 绑定 */}
      <web-ui-button onClick={() => {}} onFocus={() => {}} />

      {/* 2. kebab-case 自定义事件精确 detail，target/currentTarget 收窄到 host */}
      <web-ui-dialog
        noEscapeClose
        onopen-change={e => {
          const open: boolean = e.detail.open
          const host: WebUiDialog = e.currentTarget
          void open
          void host
        }}
      />
      <web-ui-collapse open={collapseOpen} onopen-change={e => setCollapseOpen(e.detail.open)} keep-mounted>
        <button>Trigger</button>
        <div slot="content">Content</div>
      </web-ui-collapse>

      {/* 3. 具体 Custom Element ref */}
      <web-ui-segmented ref={segmentedRef} />
      <web-ui-switch ref={switchRef} />
      <web-ui-dialog ref={dialogRef} />

      {/* 4a. 未知属性被拒绝 */}
      {/* @ts-expect-error foo 不是 web-ui-button 的合法属性 */}
      <web-ui-button foo="bar">A</web-ui-button>

      {/* 4b. 未知事件名被拒绝 */}
      {/* @ts-expect-error onFoo 不是合法事件绑定 */}
      <web-ui-button onFoo={() => {}}>A</web-ui-button>

      {/* 4c. lowercase 标准事件别名已移除，oninput 被拒绝 */}
      {/* @ts-expect-error oninput 已移除，标准事件用 onInput */}
      <web-ui-input oninput={() => {}} />

      {/* 4d. 属性类型错误被拒绝 */}
      {/* @ts-expect-error value 是 string，不接受 number */}
      <web-ui-segmented value={123} />
    </>
  )
}
